<a href="https://colab.research.google.com/github/prayasshrivastava/Machine-learning/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
a=np.array([1,2,3])    #for printing one dimensional array
print(a)

[1 2 3]


In [6]:
a=np.array([(1,2,3),(4,5,6)])    #for printing two dimensional array
print(a)

[[1 2 3]
 [4 5 6]]


In [12]:
# difference between list and numpy
import numpy as np
import time
import sys
s=range(1000)
print(sys.getsizeof(5)*len(s))    #memory  occupied by list
d=np.arange(1000)
print(d.size*d.itemsize)          #memory occupied by the numpy



28000
8000


In [18]:
import numpy as np 
a=np.array([(1,2,3),(4,5,6)])
print(a.ndim)                   #print dimension of array

2


In [19]:
print(a.itemsize)           #occupied memory
print(a.dtype)              #data type

8
int64


In [20]:
print(a.size)       # print size of array
print(a.shape)      # print shape of array

6
(2, 3)


In [22]:
b=np.array([(1,2,3,4),(5,6,7,8)])
c=b.reshape(4,2)                            #reshape the array
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [23]:
#slicing concept in numpy

print(c[3,1])


8


In [24]:
print(b[0:,2])

[3 7]


In [25]:
b=np.array([(1,2,3,4),(5,4,7,5),(7,9,5,3)])
print(b[0:2,3])

[4 5]


In [26]:
print(b[1:,[0,2]])

[[5 7]
 [7 5]]


In [32]:
a=np.linspace(1,6,12)    # give the 12 values between 1 to 6
print(a)

[1.         1.45454545 1.90909091 2.36363636 2.81818182 3.27272727
 3.72727273 4.18181818 4.63636364 5.09090909 5.54545455 6.        ]


In [38]:
print(b.max())             # printing maximum value of array
print(b.min())             # printing minimum value f array
print(b.sum())             # printing sum of array


9
1
55


In [39]:
# Axis in numpy

a=np.array([(1,2,3,4),(5,6,7,8)])
print(a.sum(axis=0))
print(a.sum(axis=1))

[ 6  8 10 12]
[10 26]


In [42]:
print(np.sqrt(a))    # print sqare root of array
print(np.std(a))     # print std. daviation of array

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]
2.29128784747792


In [44]:
a=np.array([(1,2,3,4),(5,6,7,8)])
b=np.array([(1,2,3,4),(5,6,7,8)])
print(a+b)                              #print sum of two matrix
print(a-b)                              # print division of two matrix
print(a*b)                              # print multiplication of two array
print(a/b)                              # print division of two array

[[ 2  4  6  8]
 [10 12 14 16]]
[[0 0 0 0]
 [0 0 0 0]]
[[ 1  4  9 16]
 [25 36 49 64]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [45]:
print(np.hstack((a,b)))            # concadinate horizontally
print(np.vstack((a,b)))            # cocadinate vertically

[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [49]:
print(a.ravel())                # printing in one row

[1 2 3 4 5 6 7 8]
